# Generated by Django 4.0.3 on 2022-04-01 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newjob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_id_job', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=3000)),
                ('closed_in', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(default='2003-03-04')),
                ('image', models.ImageField(default='user_image_default.png', upload_to='jobs_images/%m')),
                ('hired', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='enterprise_description',
            field=models.CharField(blank=True, default='none', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name='UsersHired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newjob.closedjobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hired', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='closedjobs',
            name='business_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
